language: node_js
node_js:
  - "6.0"
branches:
  only:
  - master
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools rimraf cross-env
after_success:
  - npm run deploy -- --token $FIREBASE_TOKEN
